custom:
  - "https://blockchair.com/bitcoin/address/bc1qeh4hnvfr6phf2wmvz3c65s5zssz5nzculavqc9"
  - "https://etherscan.io/address/0xCd63513ec76AFf7f946D280754976f6094C6047D"
  - "https://tronscan.org/#/address/TTbqkbQ7gPvo9fdhVhGvLq7uv55kRhZ4gA"
  - "https://github.com/cathxrsys/patronus/blob/main/DONATE.md"